iPieShop.Web/Models/AppDbContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace iPieShop.Web.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }
        public DbSet<Pie> Pies { get; set; }
        public DbSet<Category> Categories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>().HasData(
                new Category()
                {
                    Id = 1,
                    Name = "Category 1"
                },
                new Category()
                {
                    Id = 2,
                    Name = "Category 2"
                },
                new Category()
                {
                    Id = 3,
                    Name = "Category 3"
                },
                new Category()
                {
                    Id = 4,
                    Name = "Category 4"
                },
                new Category()
                {
                    Id = 5,
                    Name = "Category 5"
                });

            modelBuilder.Entity<Pie>().HasData(
                new Pie()
                {
                    Id = 1,
                    CategoryId = 1,
                    Description = "SOME DESCRIPTION HERE",
                    ImageUrl = "SOME IMAGE HERE",
                    Name = "SOME NAME HERE",
                    Price = 1000
                },
                new Pie()
                {
                    Id = 2,
                    CategoryId = 2,
                    Description = "SOME DESCRIPTION HERE",
                    ImageUrl = "SOME IMAGE HERE",
                    Name = "SOME NAME HERE",
                    Price = 2000
                },
                new Pie()
                {
                    Id = 3,
                    CategoryId = 3,
                    Description = "SOME DESCRIPTION HERE",
                    ImageUrl = "SOME IMAGE HERE",
                    Name = "SOME NAME HERE",
                    Price = 3000
                },
                new Pie()
                {
                    Id = 4,
                    CategoryId = 4,
                    Description = "SOME DESCRIPTION HERE",
                    ImageUrl = "SOME IMAGE HERE",
                    Name = "SOME NAME HERE",
                    Price = 4000
                });

            base.OnModelCreating(modelBuilder);
        }
    }
}

iPieShop.Web/Models/Category.cs
using System.Collections.Generic;

namespace iPieShop.Web.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public List<Pie> Pies { get; set; }
    }
}

iPieShop.Web/Models/CategoryRepository.cs
using System.Collections.Generic;
using System.Linq;

namespace iPieShop.Web.Models
{
    public class CategoryRepository : ICategoryRepository
    {
        private readonly AppDbContext _appDbContext;
        public CategoryRepository(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IEnumerable<Category> GetCategories()
        {
            return _appDbContext.Categories;
        }
    }
}

iPieShop.Web/Models/ICategoryRepository.cs
using System.Collections.Generic;

namespace iPieShop.Web.Models
{
    public interface ICategoryRepository
    {
        IEnumerable<Category> GetCategories();
    }
}

iPieShop.Web/Models/IPieRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iPieShop.Web.Models
{
    public interface IPieRepository
    {
        IEnumerable<Pie> GetPies();
        Pie GetPie(int id);
    }
}

iPieShop.Web/Models/Pie.cs
using System;
using System.Linq;
using System.Threading.Tasks;

namespace iPieShop.Web.Models
{
    public class Pie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

iPieShop.Web/Models/PieRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace iPieShop.Web.Models
{
    public class PieRepository : IPieRepository
    {
        private readonly AppDbContext _appDbContext;
        public PieRepository(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        public IEnumerable<Pie> GetPies()
        {
            return _appDbContext.Pies;
        }

        public Pie GetPie(int id)
        {
            return _appDbContext.Pies.Find(id);
        }
    }
}

iPieShop.Web/ViewModels/PieListViewModel.cs
using System.Collections.Generic;
using iPieShop.Web.Models;

namespace iPieShop.Web.ViewModels
{
    public class PieListViewModel
    {
        public IEnumerable<Pie> Pies { get; set; }
        public string SelectedCategory { get; set; }
    }
}

iPieShop.Web/Controllers/PieController.cs
using iPieShop.Web.Models;
using iPieShop.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace iPieShop.Web.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _iPieRepository;
        private readonly ICategoryRepository _iCategoryRepository;

        public PieController(IPieRepository iPieRepository,ICategoryRepository iCategoryRepository)
        {
            _iPieRepository = iPieRepository;
            _iCategoryRepository = iCategoryRepository;
        }

        [HttpGet]
        public ActionResult List()
        {
            var data = new PieListViewModel()
            {
                Pies = _iPieRepository.GetPies(),
                SelectedCategory = "SOME SELECTED CATEGORY"
            };
            return View(data);
        }
        
        [HttpGet]
        public ActionResult Detail(int id)
        {
            var data = _iPieRepository.GetPie(id);

            return View(data);
        }
    }
}

iPieShop.Web/Views/Pie/Detail.cshtml
@model Pie
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Price</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.CategoryId</td>
            <td>@Model.Description</td>
            <td>@Model.Price</td>
            <td>@Model.ImageUrl</td>
        </tr>
    </tbody>
</table>

iPieShop.Web/Views/Pie/List.cshtml
@model PieListViewModel
<h3>@Model.SelectedCategory</h3>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pie in Model.Pies)
        {
            <tr>
                <td>@pie.Id</td>
                <td>
                    <a asp-controller="Pie" asp-action="Detail" asp-route-id="@pie.Id">
                        @pie.Name
                    </a>
                </td>
                <td>@pie.Price</td>
                <td>@pie.ImageUrl</td>
            </tr>
        }
    </tbody>
</table>

iPieShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>